bitbag_sylius_wishlist_plugin_shop:
    resource: "@BitBagSyliusWishlistPlugin/Resources/config/routing.yml"

artis_wishlist_plugin_shop_api:
    resource: "@DHArtisWishlistPlugin/Resources/config/routing/api.yml"
    prefix: /shop-api
